version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: stok-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stok_user
      POSTGRES_PASSWORD: stok_pass
      POSTGRES_DB: stok_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stok_user -d stok_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: stok-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stok.local
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
